### PR TITLE
Adding extra query support

### PR DESCRIPTION
**Pull request by patrioticcow**
idea:

    $usersData = $firebase->get('/users', [
	'orderBy'      => 'id',
	'startAt'      => '1',
	'limitToFirst' => '80',
    ]);

this is good for pagination and other things.

### CODE REVIEW

**Comment by patrioticcow** [comment]
The interface can be modified to add `$data` to get. and maybe `getString()` can be improved

**Comment by mastef** [comment]
@ktamas77 this one is even better than the previous PR. Any ideas on merging this?

**Comment by innovaat** [comment]
While trying to pass a boolean as value this fails, as it is changed to a string. I have added this code to getString(197):
`			elseif($val === false)
				$str .= '&' . $key . '=false';
			elseif($val === true)
					$str .= '&' . $key . '=true';
`

**Comment by myuseringithub** [comment]
Hi thanks for applying this must feature. How can I use this with composer instead of the original respiratory ? 
I tried: 
`sudo composer require patrioticcow/firebase-php master
`
but it gives me error like: 

> Problem 1
    - The requested package patrioticcow/firebase-php could not be found in any
 version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your mi
nimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more de
tails.

Could you guide me to the correct solution ?

**Comment by ktamas77** [comment]
Extra query parameters can be added from V2.1.0

**Pull request closed without merging**
