### PR TITLE
Added options parameter to GET request

### PR DESCRIPTION
**Pull request by Shay12tg**
So we can do this:
 $firebase->get('chatroom/1337', ['orderBy' => '"timestamp"', 'limitToLast' => 3])

### CODE REVIEW

**Comment by alexsup** [comment]
:+1:

**Comment by arielcxl** [comment]
:+1:

**Comment by myuseringithub** [comment]
Hi there, thanks for the contribution. 
The orderBy doesn't seem to work for me, although my setup of firebase security seems to be fine. 
I made sure that I'm using your modified fork in my project.

PHP code: 
`  $firebaseData['conditions'] = json_decode($firebase->get(
DEFAULT_PATH  . '/domains/'. $domain . '/conditions', ['orderBy' => '"order"']
), true);
`

Firebase security rules: 
`        "domains": {
          "$uid": {
            "conditions": {
                ".indexOn": ["order"]
            }
          }
        }
`

Firebase Data: 
firebase

**Comment by myuseringithub** [comment]
ANSWER - no sorting in REST API
rest api

**Comment by ktamas77** [comment]
@Shay12tg since there is no sorting in the REST api, i'll close this request for now.
Thank you for your contribution.

**Pull request closed without merging**
